SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS RIGHT JOIN ANIMAL_OUTS  AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NOT NULL
ORDER BY OUTS.DATETIME - INS.DATETIME DESC LIMIT 2