SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME 
FROM ANIMAL_INS AS INS 
LEFT JOIN ANIMAL_OUTS AS OUTS 
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE "Intact%"
AND OUTS.SEX_UPON_OUTCOME IN("Spayed Female", "Spayed Male", "Neutered Female", "Neutered Male")